In [2]:
import pandas as pd
import seaborn as sns

In [3]:
insurance_data = pd.read_csv("data\\insurance.csv")

In [4]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

# ONE HOT ENCODING

In [5]:
X= insurance_data.drop(columns=["charges"])
y= insurance_data["charges"]

X= pd.get_dummies(X,columns=['region'],drop_first=True, dtype = int)

#MAPPING
X["sex"] = X["sex"].map({"female":1,"male":0})
X["smoker"] = X["smoker"].map({"yes":1,"no":0})

In [6]:
X.head()

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
0,19,1,27.900,0,1,0,0,1
1,18,0,33.770,1,0,0,1,0
2,28,0,33.000,3,0,0,1,0
3,33,0,22.705,0,0,1,0,0
4,32,0,28.880,0,0,1,0,0

##### now the region is divided into 4 categories and only one of them is true(1) by one hot encoding

# Interaction Features

In [7]:
X['age_smoker'] = X['age']*X['smoker']
X['bmi_smoker'] = X['bmi']*X['smoker']

In [8]:
X.head()

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest,age_smoker,bmi_smoker
0,19,1,27.900,0,1,0,0,1,19,27.9
1,18,0,33.770,1,0,0,1,0,0,0.0
2,28,0,33.000,3,0,0,1,0,0,0.0
3,33,0,22.705,0,0,1,0,0,0,0.0
4,32,0,28.880,0,0,1,0,0,0,0.0

In [9]:
#train_test_split
from sklearn.model_selection import train_test_split

X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [10]:
#evaluate

from sklearn.metrics import r2_score

r2 = r2_score(y_test,y_pred)
print(r2)

0.865231697953168

###  more feature engineering terms:
    -> Scaling numerical features
    -> create useful derived features
    -> feature selection